version: '3.8'

services:
  # Cấu hình cho Website PHP
  web-app:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql-db
    networks:
      - my-network

  # Cấu hình cho Database MySQL
  mysql-db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: shop_db
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      # Tự động import file sql của bạn khi chạy lần đầu
      - ./Adminpage/shop_db.sql:/docker-entrypoint-initdb.d/shop_db.sql
    networks:
      - my-network

  node-app:
    build: ./Clothing-Management-master  # <-- Tên thư mục Node của bạn
    ports:
      - "3000:3000"
    depends_on:
      - mongo-db  # <-- Bắt buộc phải đợi Mongo chạy xong mới chạy web
    networks:
      - my-network

  # --- THÊM CÁI NÀY: Database MongoDB ---
  mongo-db:
    image: mongo:4.4
    ports:
      - "27017:27017"
    networks:
      - my-network

networks:
  my-network: